#!/bin/bash

# -------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2018 Adam Mackiewicz <a.mackiewicz@webcitron.eu>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# -------------------------------------------------------

reposDirectories=(
	directory1
	directory2
)
sshPublicKeyPath="XXX"

currentDirectory="$PWD"

for repoDirectory in ${reposDirectories[*]}; do
	logPrefix="[$(date '+%d/%m/%Y %H:%M:%S') ${repoDirectory}] "

	ssh-agent bash -c "
printf '${logPrefix}'; 
ssh-add ${sshPublicKeyPath}; 
cd ${currentDirectory}/${repoDirectory};	

printf '${logPrefix}'; 
git stash save;
 
git checkout master &>/dev/null;

printf '${logPrefix}';
git fetch upstream;
git merge upstream/master;

printf '${logPrefix}'; 
git push;
"
done
